apiVersion: v1
kind: ConfigMap
metadata:
  name: constant-storage
  namespace: {{ .Values.namespace }}
data:
  # property-like keys; each key maps to a simple value
  namespace: {{ .Values.namespace }}
  postgres_db: {{ .Values.name_db }}
  spring_datasource_url: {{ .Values.url_db }}
