apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.username_db }}
  password: {{ .Values.password_db }}
---