apiVersion: v1
kind: Service
metadata:
  name: exercise-postgres
  namespace: {{ .Values.namespace }}
  labels:
    name: postgres-service
spec:
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
  selector:
    app: db
  clusterIP: None
---