kind: Service
apiVersion: v1
metadata:
  name: foo-app-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: proxy
    app: foo-app
  ports:
    - name: app-service-port
      protocol: TCP
      port: 80
      targetPort: 8080

---