apiVersion: v1
kind: ConfigMap
metadata:
  name: constant-storage
  namespace: exercise-java
data:
  default.conf: |
    server{
        listen  8080 default_server;
        server_name _;
        
        default_type text/plain;
      
        location / {
        return 200 '$hostname\n';
        }
    }