---
apiVersion: v1
kind: Service
metadata:
  name: exercise-postgres
  namespace: exercise-java
  labels:
    name: postgres-service
spec:
  ports:
    - name: psql
      port: 5432
      targetPort: 5432
  selector:
    app: db
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exercise-postgres
  namespace: exercise-java
  labels:
    app: exercise-postgres
    service: psql
spec:
  selector:
    matchLabels:
      app: db # has to match .spec.template.metadata.labels
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:14-alpine
          env:
            # PostgreSQL configuration
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-basic-auth
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: constant-storage
                  key: postgres_db
            - name: POSTGRESQL_LOG_HOSTNAME
              value: "true"
            - name: PGDATA
              value: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata-volume
              mountPath: /var/lib/postgresql/data
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: constant-storage

  volumeClaimTemplates:
    - metadata:
        name: pgdata-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi